preprocess:
    data_dir: '/home/tony/Documents/kits19/data/'
    output_dir: '/home/tony/Documents/gcn_preprocess/kits19_3d'
    z_crop_size: 48
    n_segments: 2048
    compactness: 0.1
    n_vertexs: 2048
    n_features: 128
    tao: 0.5

main:
    random_seed: 'kits19'
    saved_dir: '/home/tony/Documents/GCN_template/models/kits_clf_3d/train'

dataset:
    name: 'KitsClfDataset'
    kwargs:
        data_dir: '/home/tony/Documents/gcn_preprocess/kits19_3d'
        data_split_csv: '/home/tony/Documents/data_split/kits_data_split.csv'
        train_preprocessings:
        valid_preprocessings:
        augments:
        transforms:
            - name: 'ToTensor'

dataloader:
    name: 'Dataloader'
    kwargs:
        train_batch_size: 1
        valid_batch_size: 1
        shuffle: true
        num_workers: 4

net:
    name: 'ClfGCN'
    kwargs:
        n_feat: 128
        n_hide: 1024
        n_class: 2
        dropout_rate: 0.5
        
losses:
    - name: 'MyBCELoss'
      kwargs:
          weight: [0.2, 0.8]
      weight: 1.0

metrics:
    - name: 'Accuracy'
    - name: 'F1Score'

optimizer:
    name: 'Adam'
    kwargs:
        lr: 0.001
        weight_decay: 0
        amsgrad: false

logger:
    name: 'KitsClfLogger'
    kwargs:
        dummy_input: [16, 1, 128, 128]

monitor:
    name: 'Monitor'
    kwargs:
        mode: 'min'
        target: 'Loss'
        saved_freq: 10
        early_stop: 0

trainer:
    name: 'KitsClfTrainer'
    kwargs:
        device: 'cuda:0'
        num_epochs: 100
