preprocess:
    data_dir: '/home/tony/Documents/kits19/data/'
    output_dir: '/home/tony/Documents/gcn_preprocess/kits19_3d'
    n_segments: 512
    compactness: 10
    n_vertexs: 512
    n_features: 64
    tao: 0.5
    threshold: 0.5

main:
    random_seed: 'kits19'
    saved_dir: '/home/tony/Documents/GCN_template/models/kits_3d/train'

dataset:
    name: 'KitsDataset'
    kwargs:
        data_dir: '/home/tony/Documents/gcn_preprocess/kits19_3d'
        data_split_csv: '/home/tony/Documents/split/gcn_kits.csv'
        train_preprocessings:
        valid_preprocessings:
        augments:
        transforms:
            - name: 'ToTensor'

dataloader:
    name: 'Dataloader'
    kwargs:
        train_batch_size: 1
        valid_batch_size: 1
        shuffle: true
        num_workers: 4

net:
    name: 'DeepGCN'
    kwargs:
        n_feat: 64
        n_hide: 1024
        n_class: 4
        dropout_rate: 0.1
        
losses:
    - name: 'MyBCELoss'
      kwargs:
          weight: [0.2, 5.0, 1.0, 1.0]
      weight: 1.0

metrics:
    - name: 'Dice'

optimizer:
    name: 'Adam'
    kwargs:
        lr: 0.001
        weight_decay: 0
        amsgrad: false

logger:
    name: 'KitsSegLogger'
    kwargs:
        dummy_input: [16, 1, 128, 128]

monitor:
    name: 'Monitor'
    kwargs:
        mode: 'min'
        target: 'Loss'
        saved_freq: 10
        early_stop: 0

trainer:
    name: 'BrainTrainer'
    kwargs:
        device: 'cuda:0'
        num_epochs: 100
